### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by 9mm** [guilhermehn/validar-cpf#338]
Thanks for making this library. I was wondering how yours differed from some other implementations I've seen:

https://www.devmedia.com.br/validar-cpf-com-javascript/23916

https://gist.github.com/saphemmy/601ce5463502ee5daf3fdfc3b02bec04

https://www.geradorcpf.com/javascript-validar-cpf.htm

They all seem to use a similar method but yours is the most different, so I was wondering if yours accounts for all cases, or even more cases than these implementations?

**Comment by 9mm** [comment]
Also so i dont create a new issue, it doesnt look like index.d.ts is included in the npm release?

**Comment by guilhermehn** [comment]
They're all similar implementations of the "módulo 11" algorithm, but with slight differences:

- https://www.devmedia.com.br/validar-cpf-com-javascript/23916: doesn't handle formatted input (like `123.456.789-00`).
- https://gist.github.com/saphemmy/601ce5463502ee5daf3fdfc3b02bec04: doesn't handle unconventional formatting (like padded strings) and other invalid numbers like "111.111.111-11" (repeating numbers).
- https://www.geradorcpf.com/javascript-validar-cpf.htm: is basically like my version, but a bit less readable.

My version handles formatted input, unconventional/unexpected formatting and repeating numbers (invalid numbers according to regulation).

>Also so i dont create a new issue, it doesnt look like index.d.ts is included in the npm release?

Thanks for pointing it out, I'll provide a fix.

**Comment by 9mm** [comment]
awesome thanks! great library .. I appreciate it

**Comment by guilhermehn** [comment]
Just published [v3.1.1](https://github.com/guilhermehn/validar-cpf/releases/tag/v3.1.1).

**Comment by guilhermehn** [comment]
Closing this issue. Feel free to reopen if necessary.
